# On windows use dxc from vcpkg, on other platforms build it from source
if (TARGET_PLATFORM_WINDOWS OR TARGET_PLATFORM_LINUX)
    find_package(directx-headers CONFIG REQUIRED)
endif ()
if (TARGET_PLATFORM_WINDOWS)
    option(USE_D3D12_AGILITY "Use D3D12 Agility SDK" ON)
    if (USE_D3D12_AGILITY)
        find_package(directx12-agility CONFIG QUIET)
        if (NOT directx12-agility_FOUND)
            message(STATUS "D3D12 Agility SDK not found, will use system D3D12")
        endif ()
    endif ()
    find_package(winpixevent CONFIG QUIET)
    if (winpixevent_FOUND)
        set(PIX_AVAILABLE TRUE)
    else ()
        set(PIX_AVAILABLE FALSE)
    endif ()
endif ()

if (TARGET_PLATFORM_WINDOWS OR TARGET_PLATFORM_LINUX)
    find_package(volk CONFIG REQUIRED)
    find_package(Vulkan REQUIRED)
    find_package(VulkanMemoryAllocator CONFIG REQUIRED)
endif ()

find_package(SDL3 CONFIG REQUIRED)
find_package(wil CONFIG REQUIRED)
find_package(directxmath CONFIG REQUIRED)
find_package(spdlog CONFIG REQUIRED)
find_package(Freetype REQUIRED)
find_package(harfbuzz CONFIG REQUIRED)
find_package(msdfgen CONFIG REQUIRED)
find_package(miniz CONFIG REQUIRED)
find_package(Stb REQUIRED)
find_path(CGLTF_INCLUDE_DIRS "cgltf.h")

set(OZZ_ANIMATION_DIR "${CMAKE_CURRENT_SOURCE_DIR}/_ThirdParty/ozz-animation")
if (EXISTS "${OZZ_ANIMATION_DIR}")
    set(OZZ_ANIMATION_INCLUDE_DIR "${OZZ_ANIMATION_DIR}/include")
    set(OZZ_ANIMATION_FOUND TRUE)
else ()
    message(FATAL_ERROR "ozz-animation not found in _ThirdParty directory")
endif ()


if (CRT_LINKAGE_STATIC EQUAL 1)
    set(ozz_build_msvc_rt_dll OFF CACHE BOOL "Select msvc DLL runtime library" FORCE)
    set(MSDF_ATLAS_DYNAMIC_RUNTIME OFF CACHE BOOL "Link dynamic runtime library instead of static" FORCE)
else ()
    set(ozz_build_msvc_rt_dll ON CACHE BOOL "Select msvc DLL runtime library" FORCE)
    set(MSDF_ATLAS_DYNAMIC_RUNTIME ON CACHE BOOL "Link dynamic runtime library instead of static" FORCE)
endif ()

set(ozz_build_tests OFF CACHE BOOL "Don't build ozz samples" FORCE)
set(ozz_build_samples OFF CACHE BOOL "Don't build ozz samples" FORCE)
set(ozz_build_howtos OFF CACHE BOOL "Don't build ozz howtos" FORCE)

if (TARGET_PLATFORM_LINUX)
    set(CMAKE_POSITION_INDEPENDENT_CODE ON)
endif ()

set(BUILD_SHARED_LIBS_TEMP ${BUILD_SHARED_LIBS})
set(BUILD_SHARED_LIBS OFF)
set(CMAKE_SKIP_INSTALL_RULES ON)

if (TARGET_PLATFORM_WINDOWS)
    if (CRT_LINKAGE_STATIC)
        if (POLICY CMP0091)
            cmake_policy(SET CMP0091 NEW)
        endif ()
        set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
    endif ()
    add_subdirectory(_ThirdParty/D3D12MemoryAllocator EXCLUDE_FROM_ALL)
endif ()
set(ozz_build_tools OFF CACHE BOOL "Don't build ozz tools" FORCE)
add_subdirectory(_ThirdParty/ozz-animation EXCLUDE_FROM_ALL)

if (MSVC)
    foreach(ozz_target ozz_animation ozz_animation_offline ozz_base ozz_geometry ozz_options)
        if (TARGET ${ozz_target})
            target_compile_options(${ozz_target} PRIVATE /wd4324)
        endif ()
    endforeach()
endif ()

set(MSDF_ATLAS_BUILD_STANDALONE OFF CACHE BOOL "Build the msdf-atlas-gen standalone executable")
set(MSDF_ATLAS_USE_SKIA OFF CACHE BOOL "Build with the Skia library")
set(MSDF_ATLAS_NO_ARTERY_FONT ON CACHE BOOL "Disable Artery Font export and do not require its submodule")
set(MSDFGEN_USE_SKIA OFF CACHE BOOL "Build msdfgen with the Skia library")
set(MSDFGEN_VCPKG_FEATURES_SET ON CACHE BOOL "Use vcpkg features")
set(VCPKG_MANIFEST_NO_DEFAULT_FEATURES ON CACHE BOOL "Disable default features")

add_subdirectory(_ThirdParty/msdf-atlas-gen EXCLUDE_FROM_ALL)
set(CMAKE_SKIP_INSTALL_RULES OFF)
set(BUILD_SHARED_LIBS ${BUILD_SHARED_LIBS_TEMP})