name: 'Setup vcpkg binary caching'
description: 'Setup vcpkg binary caching'
inputs:
  vcpkg-json-path:
    description: 'Path to vcpkg.json file'
    required: false
    default: 'vcpkg.json'

runs:
  using: "composite"
  steps:
    - name: Configure vcpkg caching
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      shell: bash

    - name: Create binary cache directory
      run: mkdir -p ${{ github.workspace }}/vcpkg/bincache
      shell: bash

    - name: Restore vcpkg
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/vcpkg
          !${{ github.workspace }}/vcpkg/buildtrees
          !${{ github.workspace }}/vcpkg/packages
          !${{ github.workspace }}/vcpkg/downloads
          !${{ github.workspace }}/vcpkg/installed
        key: vcpkg-${{ runner.os }}-${{ hashFiles(inputs.vcpkg-json-path) }}

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: ${{ inputs.vcpkg-json-path }}
      env:
        VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
        VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
      shell: bash