if (WIN32)
    add_definitions(-D_WIN32=1)
endif()

if (UNIX AND NOT APPLE)
    add_definitions(-D__linux__=1)
    add_definitions(-DLINUX=1)
endif()

if (EMSCRIPTEN)
    add_definitions(-DEMSCRIPTEN=1)
endif()

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}")
foreach(OUTPUTCONFIG ${CMAKE_CONFIGURATION_TYPES})
    string(TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${PROJECT_BINARY_DIR}")
endforeach()

if (NOT CPU_ARCHITECTURE)
    if (APPLE)
        set(CPU_ARCHITECTURE "arm64")
    elseif (EMSCRIPTEN)
        set(CPU_ARCHITECTURE "wasm32")
    elseif (CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64" OR MSVC_CXX_ARCHITECTURE_ID STREQUAL "ARM64")
        set(CPU_ARCHITECTURE "arm64")
    elseif (CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(CPU_ARCHITECTURE "x64")
    else()
        set(CPU_ARCHITECTURE "x86")
    endif ()
endif()

set(CMAKE_CXX_STANDARD 20)

set(TARGET_PLATFORM_WINDOWS FALSE)
set(TARGET_PLATFORM_MACOS FALSE)
set(TARGET_PLATFORM_LINUX FALSE)
set(TARGET_PLATFORM_WEB FALSE)

option(BUILD_WEBGPU_NATIVE "Build native WebGPU, useful for debugging webgpu locally before releasing to emscripten" OFF)

if (EMSCRIPTEN)
    set(TARGET_PLATFORM_WEB TRUE)
elseif (WIN32)
    set(TARGET_PLATFORM_WINDOWS TRUE)
elseif (APPLE)
    set(TARGET_PLATFORM_MACOS TRUE)
elseif (UNIX AND NOT APPLE)
    set(TARGET_PLATFORM_LINUX TRUE)
endif()