if (WIN32)
    add_definitions(-D_WIN32=1)
endif()

set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${PROJECT_BINARY_DIR}")
foreach(OUTPUTCONFIG ${CMAKE_CONFIGURATION_TYPES})
    string(TOUPPER ${OUTPUTCONFIG} OUTPUTCONFIG)
    set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_${OUTPUTCONFIG} "${PROJECT_BINARY_DIR}")
endforeach()

if (NOT CPU_ARCHITECTURE)
    if (APPLE)
        set(CPU_ARCHITECTURE "arm64")
    else()
        if (CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(CPU_ARCHITECTURE "x64")
        else()
            set(CPU_ARCHITECTURE "x86")
        endif ()
    endif ()
endif()

set(CMAKE_CXX_STANDARD 23)